jobs:
  include:
    - sudo: required
      services:
        - docker
      language: generic
      before_install: docker pull carto/nodejs-xenial-pg101:latest
      script: npm run docker-test -- 10.15.1 # Node.js version
