sudo: false

addons:
  postgresql: "9.3"
  apt:
    packages:
    - postgresql-plpython-9.3
    - pkg-config
    - libcairo2-dev
    - libjpeg8-dev
    - libgif-dev

before_install:
  - createdb template_postgis
  - psql -c "CREATE EXTENSION postgis" template_postgis
  - psql -c "CREATE EXTENSION plpython" template_postgis

env:
  - NPROCS=1 JOBS=1 PGUSER=postgres

language: node_js
node_js:
  - "0.10"

notifications:
  irc:
    channels:
      - "irc.freenode.org#cartodb"
    use_notice: true
