language: generic
sudo: required
env:
  global:
    - VERSION=1.${TRAVIS_BUILD_NUMBER}
  matrix:
    - NODE_VERSION=10.15.1
      DOCKER_IMAGE=carto/nodejs-xenial-pg101:latest
    - NODE_VERSION=10.15.1
      DOCKER_IMAGE=carto/nodejs-xenial-pg1121:latest
services:
  - docker
before_install: docker pull ${DOCKER_IMAGE}
script: npm run docker-test -- ${DOCKER_IMAGE} ${NODE_VERSION}
