addons:
  postgresql: "9.3"

before_install:
  - createdb template_postgis
  - psql -c "CREATE EXTENSION postgis" template_postgis

before_script:
  # Tell npm to use known registrars:
  # see http://blog.npmjs.org/post/78085451721/npms-self-signed-certificate-is-no-more
  - npm config set ca ""

env:
  - NPROCS=1 JOBS=1 PGUSER=postgres

language: node_js
node_js:
  - "0.8"
  - "0.10"

notifications:
  irc:
    channels:
      - "irc.freenode.org#cartodb"
    use_notice: true
