dist: trusty
addons:
  postgresql: "9.5"
  apt:
    packages:
      - postgresql-9.5-postgis-2.3
      - postgresql-plpython-9.5
      - pkg-config
      - libcairo2-dev
      - libjpeg8-dev
      - libgif-dev
      - libpango1.0-dev
      - g++-4.9

before_install:
  - createdb template_postgis
  - createuser publicuser
  - psql -c "CREATE EXTENSION postgis" template_postgis

env:
  - NPROCS=1 JOBS=1 PGUSER=postgres CXX=g++-4.9

language: node_js
node_js:
  - "0.10"
  - "6"
