dist: trusty # only environment that supports Postgres 9.5 at this time
sudo: required
addons:
  postgresql: "9.5"
  apt:
    packages:
      - postgresql-plpython-9.5
      - pkg-config
      - libcairo2-dev
      - libjpeg8-dev
      - libgif-dev
      - libpango1.0-dev

before_install:
  - createdb template_postgis
  - createuser publicuser
  - psql -c "CREATE EXTENSION postgis" template_postgis

env:
  - NPROCS=1 JOBS=1 PGUSER=postgres

language: node_js
node_js:
  - "0.10"
