sudo: required
dist: trusty

services:
  - docker

before_install:
  - docker pull cartoimages/windshaft-carto-testing

script:
  - docker run -v `pwd`:/srv cartoimages/windshaft-carto-testing -e POSTGIS_VERSION=2.4

language: generic

