sudo: required
dist: xenial

services:
  - docker

before_install:
  - docker pull cartoimages/windshaft-testing

script:
  - docker run -e POSTGIS_VERSION=2.4 -v `pwd`:/srv cartoimages/windshaft-testing bash run_tests_docker.sh

language: generic
