before_install:
  - sudo apt-add-repository --yes ppa:mapnik/v2.1.0
  - sudo apt-get update -q
  - sudo apt-get install -q libmapnik-dev
  - createdb template_postgis
  - psql -c "CREATE EXTENSION postgis" template_postgis
  # Tell npm to use known registrars:
  # see http://blog.npmjs.org/post/78085451721/npms-self-signed-certificate-is-no-more
  - npm config set ca ""

env:
  - NPROCS=1 JOBS=1

language: node_js
node_js:
  - "0.8"
  - "0.10"

notifications:
  irc:
    channels:
      - "irc.freenode.org#cartodb"
    use_notice: true
